---
title: Field Guides
page-layout: full
toc-location: right
---

These field guides provide applied researchers with 
curated lists of tutorials, case studies, and resources
which contain Stan implementations of the most commonly used models in their domain.
If you would like to contribute one for your field,
see this Discourse post:  [Fostering Stan user communities through domain-specific resource pages ](https://discourse.mc-stan.org/t/fostering-stan-user-communities-through-domain-specific-resource-pages/11544){target="_blank"}


## [Education Research Using Stan](https://education-stan.github.io){target="_blank"}

* Topics:  Item Response Theory, Cognitive Diagnosis Models, Multilevel Modeling
* Maintainer: [Sofia Rabe-Hesketh](https://bse.berkeley.edu/sophia-rabe-hesketh){target="_blank"}


## [Stan for Ecology](https://stanecology.github.io/){target="_blank"}

* Topics:  Ecological times series models, population models, predator-prey dynamics, species site-occupancy models.
* Maintainer: [Vianey Leos Barajas](https://www.statistics.utoronto.ca/people/directories/all-faculty/vianey-leos-barajas){target="_blank"}

## [Stan for Epidemiology](https://epidemiology-stan.github.io/){target="_blank"}

* Topics:  Disease transmission (SIR models), disease mapping (ICAR, BYM models), survival analysis, longitudinal data.
* Maintainer: [Léo Grinsztajn](https://www.isir.upmc.fr/personnel/grinsztajn/){target="_blank"}

  
## [Stan for Cognitive Science](https://cognitive-science-stan.github.io/){target="_blank"}

* Cognitive Science and Neuroscience papers which use Stan, brms, or RStanArm.
* Maintainer: [Bruno Nicenboim](https://www.tilburguniversity.edu/staff/b-nicenboim){target="_blank"}

## [Applied Modelling in Drug Development](https://opensource.nibr.com/bamdd/)

* Case studies using brms which address clinical questions for drug development.
* Editor: [Sebastian Weber](mailto:sebastian.weber@novartis.com) and colleagues.
