## Open Code &amp; Reproducible Science

Stan is freedom-respecting, open-source software <span
class="note">(new BSD core, some interfaces GPLv3)</span>.&nbsp; Stan
is associated with NumFOCUS, a 501(c)(3) nonprofit supporting open code
and reproducible science, through which you can [help support
Stan](support.html#contribute-money).


## Acknowledgements {-}

Stan has grown from a small research project started in 2011 at Columbia University
to a global community of developers, researchers, and users.
The Stan project owes its success to the contributions from hundreds of
developers, researchers, active users, and funders.
Individual contributions to the software and documentation can be tracked through GitHub.

Stan has been funded through grants for Stan and its developers,
through in-kind donations in the form of companies contributing
developer time to Stan and individuals contributing their own time to
Stan, and through donations to the open-source scientific software
non-profit NumFOCUS.

We are grateful to all the users who have taken the time to file bug reports and
feature requests via the GitHub and the Stan forums; this feedback has greatly
improved Stan's usability and reliability.

## Copyright and trademark {-}

* Copyright 2011--2023, Stan Development Team and their assignees.

* The Stan name and logo are registered trademarks of NumFOCUS.


## Licensing {-}

* *Text content:*  [CC-BY ND 4.0 license](https://creativecommons.org/licenses/by-nd/4.0/legalcode)

* *Computer code:*  [BSD 3-clause license](https://opensource.org/licenses/BSD-3-Clause)

* *Logo:*  [Stan logo usage guidelines](https://mc-stan.org/about/logo/)

## Citing Stan {-}

We appreciate citations for the Stan software because it lets us find out what 
people have been doing with Stan and motivate further grant funding. See 
[How to Cite Stan](https://mc-stan.org/users/citations/) for more details.

## Contribute Expertise

We welcome new Stan contributors!

* Code

* Write

* Communicate


## Contribute Money

Stan is now linked to [NumFOCUS](https://numfocus.org/), a
U.S. 501(c)(3) nonprofit organization that serves many open-source software projects
including NumPy, Julia, Jupyter, ScikitLearn.


* [Contribute to Stan via NumFOCUS](https://numfocus.salsalabs.org/donate-to-stan) &nbsp;&nbsp; (Salsa Labs payment processing)

* [Sponsor Stan via GitHub](https://github.com/sponsors/stan-dev)

## Stan Shop

If you're looking to infer in style, stop by one of our shops for Stan
t-shirts and mugs.

* [Stan Shop [US]](https://shop.spreadshirt.com/mc-stan/)
  &nbsp; <span class="note">(Spreadshirt US)</span>

* [Stan Shop [UK]](https://shop.spreadshirt.co.uk/mc-stan/)
  &nbsp; <span class="note">(Spreadshirt UK)</span>

